INSERT INTO TBL_CARGO (ID,NOME) VALUES(1,'VENDEDOR');
INSERT INTO TBL_CARGO (ID,NOME) VALUES(2,'GERENTE');
INSERT INTO TBL_CARGO (ID,NOME) VALUES(3,'CAIXA');
INSERT INTO TBL_CARGO (ID,NOME) VALUES(4,'DIRETOR');
INSERT INTO TBL_CARGO (ID,NOME) VALUES(5,'ANALISTA DE DEPARTAMENTO PESSOAL');
INSERT INTO TBL_CARGO (ID,NOME) VALUES(6,'SERVIÇOS GERAIS');

INSERT INTO TBL_DEPARTAMENTO (ID,NOME) VALUES(1,'VENDAS');
INSERT INTO TBL_DEPARTAMENTO (ID,NOME) VALUES(2,'DIRETORIA');
INSERT INTO TBL_DEPARTAMENTO (ID,NOME) VALUES(3,'RH');


